// Code generated by protoc-gen-go.
// source: account.proto
// DO NOT EDIT!

/*
Package network_cmd is a generated protocol buffer package.

It is generated from these files:
	account.proto

It has these top-level messages:
	PBUserInfo
	PBReqAccountLogin
	PBRespAccountLogin
	PBReqAccountInfoExt
	PBRespAccountInfoExt
*/
package network_cmd

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PBUserInfo struct {
	Uid              *string `protobuf:"bytes,1,req,name=uid" json:"uid,omitempty"`
	Name             *string `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Icon             *string `protobuf:"bytes,3,req,name=icon" json:"icon,omitempty"`
	Mmoney           *int64  `protobuf:"varint,4,req,name=mmoney" json:"mmoney,omitempty"`
	Status           *int32  `protobuf:"varint,5,req,name=status" json:"status,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PBUserInfo) Reset()                    { *m = PBUserInfo{} }
func (m *PBUserInfo) String() string            { return proto.CompactTextString(m) }
func (*PBUserInfo) ProtoMessage()               {}
func (*PBUserInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PBUserInfo) GetUid() string {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return ""
}

func (m *PBUserInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *PBUserInfo) GetIcon() string {
	if m != nil && m.Icon != nil {
		return *m.Icon
	}
	return ""
}

func (m *PBUserInfo) GetMmoney() int64 {
	if m != nil && m.Mmoney != nil {
		return *m.Mmoney
	}
	return 0
}

func (m *PBUserInfo) GetStatus() int32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

type PBReqAccountLogin struct {
	Sid              *int32  `protobuf:"varint,1,req,name=sid" json:"sid,omitempty"`
	Api              *int32  `protobuf:"varint,2,req,name=api" json:"api,omitempty"`
	Type             *int32  `protobuf:"varint,3,req,name=type" json:"type,omitempty"`
	Platuid          *string `protobuf:"bytes,4,opt,name=platuid" json:"platuid,omitempty"`
	Token            *string `protobuf:"bytes,5,opt,name=token" json:"token,omitempty"`
	Lang             *int32  `protobuf:"varint,6,opt,name=lang" json:"lang,omitempty"`
	Time             *int64  `protobuf:"varint,7,opt,name=time" json:"time,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PBReqAccountLogin) Reset()                    { *m = PBReqAccountLogin{} }
func (m *PBReqAccountLogin) String() string            { return proto.CompactTextString(m) }
func (*PBReqAccountLogin) ProtoMessage()               {}
func (*PBReqAccountLogin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PBReqAccountLogin) GetSid() int32 {
	if m != nil && m.Sid != nil {
		return *m.Sid
	}
	return 0
}

func (m *PBReqAccountLogin) GetApi() int32 {
	if m != nil && m.Api != nil {
		return *m.Api
	}
	return 0
}

func (m *PBReqAccountLogin) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *PBReqAccountLogin) GetPlatuid() string {
	if m != nil && m.Platuid != nil {
		return *m.Platuid
	}
	return ""
}

func (m *PBReqAccountLogin) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

func (m *PBReqAccountLogin) GetLang() int32 {
	if m != nil && m.Lang != nil {
		return *m.Lang
	}
	return 0
}

func (m *PBReqAccountLogin) GetTime() int64 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

type PBRespAccountLogin struct {
	Code             *int32      `protobuf:"varint,1,req,name=code" json:"code,omitempty"`
	Time             *int64      `protobuf:"varint,2,opt,name=time" json:"time,omitempty"`
	User             *PBUserInfo `protobuf:"bytes,3,opt,name=user" json:"user,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *PBRespAccountLogin) Reset()                    { *m = PBRespAccountLogin{} }
func (m *PBRespAccountLogin) String() string            { return proto.CompactTextString(m) }
func (*PBRespAccountLogin) ProtoMessage()               {}
func (*PBRespAccountLogin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PBRespAccountLogin) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *PBRespAccountLogin) GetTime() int64 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func (m *PBRespAccountLogin) GetUser() *PBUserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

type PBReqAccountInfoExt struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Time             *int64  `protobuf:"varint,2,opt,name=time" json:"time,omitempty"`
	Gender           *int32  `protobuf:"varint,3,opt,name=gender" json:"gender,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PBReqAccountInfoExt) Reset()                    { *m = PBReqAccountInfoExt{} }
func (m *PBReqAccountInfoExt) String() string            { return proto.CompactTextString(m) }
func (*PBReqAccountInfoExt) ProtoMessage()               {}
func (*PBReqAccountInfoExt) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PBReqAccountInfoExt) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *PBReqAccountInfoExt) GetTime() int64 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func (m *PBReqAccountInfoExt) GetGender() int32 {
	if m != nil && m.Gender != nil {
		return *m.Gender
	}
	return 0
}

type PBRespAccountInfoExt struct {
	Code             *int32      `protobuf:"varint,1,req,name=code" json:"code,omitempty"`
	User             *PBUserInfo `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *PBRespAccountInfoExt) Reset()                    { *m = PBRespAccountInfoExt{} }
func (m *PBRespAccountInfoExt) String() string            { return proto.CompactTextString(m) }
func (*PBRespAccountInfoExt) ProtoMessage()               {}
func (*PBRespAccountInfoExt) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PBRespAccountInfoExt) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *PBRespAccountInfoExt) GetUser() *PBUserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*PBUserInfo)(nil), "network.cmd.PBUserInfo")
	proto.RegisterType((*PBReqAccountLogin)(nil), "network.cmd.PBReqAccountLogin")
	proto.RegisterType((*PBRespAccountLogin)(nil), "network.cmd.PBRespAccountLogin")
	proto.RegisterType((*PBReqAccountInfoExt)(nil), "network.cmd.PBReqAccountInfoExt")
	proto.RegisterType((*PBRespAccountInfoExt)(nil), "network.cmd.PBRespAccountInfoExt")
}

func init() { proto.RegisterFile("account.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 324 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0xcd, 0x6a, 0xc3, 0x30,
	0x10, 0x84, 0x91, 0x6d, 0x25, 0x64, 0x43, 0xa1, 0x55, 0x43, 0xaa, 0xa3, 0xf0, 0xc9, 0x50, 0xf0,
	0xa1, 0x6f, 0xd0, 0x40, 0x0f, 0x85, 0x1e, 0x82, 0x20, 0xf4, 0x6c, 0x6c, 0x35, 0x88, 0xc4, 0x92,
	0x6b, 0xc9, 0x6d, 0xf3, 0x3c, 0x7d, 0xd1, 0xb2, 0x8a, 0xf2, 0x47, 0x2e, 0xbd, 0x7d, 0x3b, 0xb6,
	0x76, 0x66, 0x07, 0x6e, 0xaa, 0xba, 0xb6, 0x83, 0xf1, 0x65, 0xd7, 0x5b, 0x6f, 0xd9, 0xd4, 0x28,
	0xff, 0x6d, 0xfb, 0x4d, 0x59, 0xb7, 0x4d, 0xfe, 0x05, 0xb0, 0x5c, 0xac, 0x9c, 0xea, 0x5f, 0xcd,
	0x87, 0x65, 0xb7, 0x90, 0x0e, 0xba, 0xe1, 0x44, 0x24, 0xc5, 0x44, 0x22, 0x32, 0x06, 0x99, 0xa9,
	0x5a, 0xc5, 0x93, 0x20, 0x05, 0x46, 0x4d, 0xd7, 0xd6, 0xf0, 0x74, 0xaf, 0x21, 0xb3, 0x39, 0x8c,
	0xda, 0xd6, 0x1a, 0xb5, 0xe3, 0x99, 0x48, 0x8a, 0x54, 0xc6, 0x09, 0x75, 0xe7, 0x2b, 0x3f, 0x38,
	0x4e, 0x45, 0x52, 0x50, 0x19, 0xa7, 0xfc, 0x97, 0xc0, 0xdd, 0x72, 0x21, 0xd5, 0xe7, 0xf3, 0x3e,
	0xdb, 0x9b, 0x5d, 0x6b, 0x83, 0xfe, 0x2e, 0xfa, 0x53, 0x89, 0x88, 0x4a, 0xd5, 0xe9, 0x60, 0x4f,
	0x25, 0x22, 0xba, 0xfb, 0x5d, 0xa7, 0x82, 0x3b, 0x95, 0x81, 0x19, 0x87, 0x71, 0xb7, 0xad, 0x3c,
	0x66, 0xcf, 0x04, 0x29, 0x26, 0xf2, 0x30, 0xb2, 0x19, 0x50, 0x6f, 0x37, 0xca, 0x70, 0x1a, 0xf4,
	0xfd, 0x80, 0x3b, 0xb6, 0x95, 0x59, 0xf3, 0x91, 0x20, 0xb8, 0x03, 0x39, 0xec, 0xd5, 0xad, 0xe2,
	0x63, 0x41, 0x8a, 0x54, 0x06, 0xce, 0x35, 0x30, 0x0c, 0xe9, 0xba, 0x8b, 0x94, 0x0c, 0xb2, 0xda,
	0x36, 0x2a, 0xc6, 0x0c, 0x7c, 0x7c, 0x9d, 0x9c, 0x5e, 0xb3, 0x47, 0xc8, 0x06, 0xa7, 0x7a, 0x9e,
	0x0a, 0x52, 0x4c, 0x9f, 0x1e, 0xca, 0xb3, 0xde, 0xcb, 0x53, 0xe9, 0x32, 0xfc, 0x94, 0xaf, 0xe0,
	0xfe, 0xbc, 0x0f, 0xfc, 0xf2, 0xf2, 0xe3, 0x8f, 0xfd, 0x93, 0xcb, 0xfe, 0xaf, 0xbc, 0xe6, 0x30,
	0x5a, 0x2b, 0xd3, 0x44, 0x37, 0x2a, 0xe3, 0x94, 0xbf, 0xc3, 0xec, 0xe2, 0x82, 0xb3, 0xbd, 0x57,
	0x37, 0x1c, 0xf2, 0x26, 0xff, 0xc8, 0xfb, 0x17, 0x00, 0x00, 0xff, 0xff, 0x50, 0x94, 0x3c, 0x61,
	0x55, 0x02, 0x00, 0x00,
}
